In [9]:
# index slicing
import numpy as np
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)
row_rank1 = an_array[1,:]
print(row_rank1, row_rank1.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
[21 22 23 24] (4,)


In [10]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [11]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, col_rank1.shape)
print(col_rank2, col_rank2.shape)

[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)


In [13]:
# More array indexing
an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44]])
print('Original Array : \n', an_array)
print(an_array.shape)

Original Array : 
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
(4, 4)


In [25]:
row_indices = np.arange(4)
# row_indices = np.arange(5)
col_indices = np.array([0,1,2,0])
print(row_indices)
print(col_indices)
print(zip(row_indices,col_indices))

[0 1 2 3]
[0 1 2 0]


In [26]:
for row, col in zip(row_indices,col_indices) :
    print(row, " ", col)

0   0
1   1
2   2
3   0


In [27]:
print("Values : \n", an_array[row_indices, col_indices])

Values : 
 [11 22 33 41]


In [30]:
# Boolean indexing (1)
an_array = np.array([[11,12],[21,22],[31,32]])
filter = (an_array > 15)

print(an_array)
print(filter)

print(an_array[filter])

an_array[an_array>15]

[[11 12]
 [21 22]
 [31 32]]
[[False False]
 [ True  True]
 [ True  True]]
[21 22 31 32]


array([21, 22, 31, 32])

In [35]:
an_array[(an_array > 20) & (an_array < 30)]

array([21])

In [36]:
print(an_array[an_array % 2 == 0])
an_array[an_array % 2 == 0] += 100
print(an_array)

[312 322 332]
[[ 11 412]
 [ 21 422]
 [ 31 432]]


In [39]:
a = np.arange(15).reshape((3,5))
print(a)
br = (a % 3 == 0)
print(b)
a[b]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]]


array([ 0,  3,  6,  9, 12])

In [44]:
# Datatypes
ex1 = np.array([11,12])
ex2 = np.array([11.0, 12.0])
ex3 = np.array([11,12], dtype=np.int64)
print(ex1.dtype)
print(ex2.dtype)
print(ex3.dtype)
print(" ")

ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4)
print(ex4.dtype)
ex5 = np.array([11,12], dtype=np.float64)
print(ex5)
print(ex5.dtype)

int32
float64
int64
 
[11 12]
int64
[11. 12.]
float64


In [47]:
# Arithmetic array operation 산술연산
x = np.array([[111,112],[121,122]], dtype = np.int)
y = np.array([[211.1,212.1], [221.1,222.2]], dtype = np.float64)
print(x+y)
print(np.add(x,y))
print(" ")
print(x-y)
print(np.subtract(x,y))
print(" ")
print(x/y)
print(np.divide(x,y))
print(" ")
print(np.sqrt(x))
print(np.exp(x))

[[322.1 324.1]
 [342.1 344.2]]
[[322.1 324.1]
 [342.1 344.2]]
 
[[-100.1 -100.1]
 [-100.1 -100.2]]
[[-100.1 -100.1]
 [-100.1 -100.2]]
 
[[0.52581715 0.52805281]
 [0.54726368 0.54905491]]
[[0.52581715 0.52805281]
 [0.54726368 0.54905491]]
 
[[10.53565375 10.58300524]
 [11.         11.04536102]]
[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [48]:
# Reshaping
a = np.array(range(8))
print(a)
print(a.shape)
b = a.reshape((a.shape[0],1))
print(b)
print(b.shape)
c = a.reshape(2,4)
print(c)
d = a.reshape(2,2,2)
print(d)

[0 1 2 3 4 5 6 7]
(8,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [61]:
# Random number generation
arr = np.random.randn(2,5) # 평균 0, 표준편차 1인 임의의 random 2X5 matrix
print(arr)
print()
arr = np.random.rand(2,5) # 0과 1사이의 random 2X5 matrix
print(arr)
print()
arr = np.random.normal(50, .1, 5) # 평균 50, 표준편차 0,1, 갯수 5개
print(arr)

[[-0.43834755  0.01506244 -0.35381788  0.92015742 -0.12705607]
 [-0.27629584  0.94401054  0.5526963  -1.18610356 -0.02149317]]

[[0.72392612 0.45510462 0.71944542 0.61228178 0.02763326]
 [0.89706713 0.41360867 0.26209046 0.85604513 0.49406261]]

[50.03503139 49.92019287 50.06731877 49.86436309 50.01116816]


In [62]:
# Numpy axis
arr = np.random.randn(2,5)
print(arr.mean()) # 총 평균 계산
print(arr.mean(axis=1)) # row별로 묶어서 평균값 게산
print(arr.mean(axis=0)) # column별로 묶어서 평균값 계산

print(arr.sum()) # 총 합계 계산
print(arr.sum(axis=1)) # row별로 묶어서 총합 게산
print(arr.sum(axis=0)) # column별로 묶어서 총합 계산

0.05126877637699904
[-0.02960464  0.1321422 ]
[ 1.23051204  0.0319196  -0.16765152 -0.32159978 -0.51683645]
0.5126877637699904
[-0.14802321  0.66071098]
[ 2.46102408  0.06383919 -0.33530304 -0.64319956 -1.0336729 ]


In [63]:
# Sorting and set operations
unsorted = np.random.randn(10)
print(unsorted)
sorted = np.array(unsorted)
sorted.sort()
print(sorted)

[ 2.51362726 -1.31404768  0.6160488   0.2048978   0.84750154 -1.02625197
 -0.95412948  0.91643459 -0.99240513  0.62858482]
[-1.31404768 -1.02625197 -0.99240513 -0.95412948  0.2048978   0.6160488
  0.62858482  0.84750154  0.91643459  2.51362726]


In [64]:
# finding unique elements
array = np.array([1,2,3,1,2,3])
np.unique(array)

array([1, 2, 3])

In [65]:
# set operation
s1 = np.array(["desk", "chair", "bulb"])
s2 = np.array(["lamp", "bulb", "chair"])
print(np.intersect1d(s1,s2))
print(np.union1d(s1,s2))
print(np.setdiff1d(s1,s2))
print(np.in1d(s1,s2)) # s1의 원소가 s2에도 있는지

['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


In [67]:
# Broadcasting example 

start = np.zeros((4,3))
add_rows = np.array([1,0,2])
print(start)
print(add_rows)

y = start + add_rows
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 0 2]
[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [68]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)
y = start + add_cols
print(y)

[[0]
 [1]
 [2]
 [3]]
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [69]:
add_scalar = np.array([1])
print(add_scalar)
print(start + add_scalar)

[1]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
%matplotlib inline
import scipy.misc
import matplotlib.pyplot as plt
from skimage import data
scipy.misc.imread()
# photo_data = misc.imread("sd-3layers.jpg")
# type(photo_data)

AttributeError: module 'scipy.misc' has no attribute 'imread'