In [2]:
import numpy as np
height = [170,180,170]
weight = [60,70,65]

np_height = np.array(height)
np_weight = np.array(weight)
np_weight / np_height

array([0.35294118, 0.38888889, 0.38235294])

In [3]:
print(type(np_weight))

<class 'numpy.ndarray'>


In [4]:
np.array([1,3,4,5])

array([1, 3, 4, 5])

In [5]:
data = [[1,2],[11,22],[111,222]]
a = np.array(data)
print(a)
print(type(a))

[[  1   2]
 [ 11  22]
 [111 222]]
<class 'numpy.ndarray'>


In [7]:
# as a range of values
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
#Ndarray
a = np.array([1.0, "is", True])
print(a)

['1.0' 'is' 'True']


In [16]:
python_list = [1,2,3]
np_list = np.array([1,2,3])
print(python_list + python_list)
print(np_list)

[1, 2, 3, 1, 2, 3]
[1 2 3]


In [17]:
# Subsetting
bmi = np.array([10,30,50,70])
print(bmi[2])
print(bmi > 35)
print(bmi[bmi>35])

50
[False False  True  True]
[50 70]


In [22]:
an_array = np.array([[1,2,3,4,5],[11,12,13,14,15]])
print(an_array)
print(an_array[0])
print(an_array[0][2])
print(an_array[0,2])
print(an_array[:,1:3])

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[1 2 3 4 5]
3
3
[[ 2  3]
 [12 13]]


In [26]:
# Numpy Utilities
print(np.zeros((2,2))) # create 2X2 array of zeros
print(np.full((2,2), 9.0)) # create a 2X2 array filled with 9
print(np.eye(2,2)) # create a 2X2 matrix with the diagonal 1s and the other 0s
print(np.ones((2,2))) # create a array of ones
print(np.random.random((2,2))) # create an array of random floats between 0 and 1

[[0. 0.]
 [0. 0.]]
[[9. 9.]
 [9. 9.]]
[[1. 0.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]]
[[0.75657287 0.05727745]
 [0.59214854 0.45728467]]


In [29]:
an_array = np.array([[11,12,13,14], [21,22,23,24],[31,32,33,34]])
print(an_array)

a_slice = an_array[:2, 1:3]
print(a_slice)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
[[12 13]
 [22 23]]


In [36]:
# Numpy slicing Index
a = np.arange(15)
print(a)
b = a.reshape(3,5)
print(b)
print(b[:2, 2:3])
print(a[0:5:2])
print(a[::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[2]
 [7]]
[0 2 4]
[ 0  2  4  6  8 10 12 14]


In [37]:
print("Before : ", an_array[0,1]) #inspect the element at 0,1
a_slice[0,0] = 1000 # a_slice[0,0] is the same piece of data as an_array[0,1]
print("After : ", an_array[0,1])

Before :  1000
After :  1000
