In [2]:
import numpy as np
np_array = np.array([[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19]])
green = np_array[0, 1:5]
blue = np_array[1:3]
print("Green :")
print(green)
print("Blue :")
print(blue)

Green :
[1 2 3 4]
Blue :
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
# 2020.10.13 추가
np_array = np.arange(20).reshape(4,5)
print(np_array)
print()

print("Green : \n", np_array[0,1:])
print()
print("Blue : \n", np_array[1:3, :])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Green : 
 [1 2 3 4]

Blue : 
 [[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
# 2020.10.13 추가
slice_ex1 = np_array[0,:]
print("slice_ex1 :\n", slice_ex1)
print(slice_ex1.shape) #Vector로 표현
print()

slice_ex2 = np_array[0:1,:]
print("slice_ex2 :\n", slice_ex2)
print(slice_ex2.shape) #Matrix로 표현
print()

slice_ex1 :
 [0 1 2 3 4]
(5,)

slice_ex2 :
 [[0 1 2 3 4]]
(1, 5)



In [68]:
import numpy as np
np_array = np.array([[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19]])
red = np_array[::3, ::2]
print("Red :")
print(red)


Red :
[[ 0  2  4]
 [15 17 19]]


In [7]:
# 2020.10.13 추가
np_array = np.arange(20).reshape(4,5)
print(np_array)
print("Red :\n", np_array[::3, ::2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Red :
 [[ 0  2  4]
 [15 17 19]]


In [9]:
import numpy as np
an_array = np.array ([[111,222], [333,444], [555,666]])
filter =  (an_array >= 200) & (an_array <= 400) & (an_array % 2 == 0)

print("filter :")
print(filter)

filter :
[[False  True]
 [False False]
 [False False]]


In [10]:
# 2020.10.13 추가
an_array[(an_array >= 200) & (an_array <= 400) & (an_array % 2 == 0)]

array([222])

In [70]:
import numpy as np
arr = np.random.normal(100, .2, size=(2,3,4))
print(arr)

[[[ 99.91953792 100.06185809 100.12304218  99.90332255]
  [100.01913068  99.75511631 100.02694647 100.15555608]
  [100.12380945 100.13868342  99.82235418 100.16351591]]

 [[ 99.89901648  99.97810867 100.01179992  99.98060319]
  [ 99.79321335 100.39480074  99.91906236 100.00177048]
  [100.03266561  99.8970655   99.75130538  99.82315259]]]


In [11]:
# 2020.10.13 추가, 0~1 사이의 random한 값을 가진 2ㅡ2 shape matrix 생성
print(np.random.random((2,2)))

[[0.63440308 0.49884551]
 [0.78088304 0.20412003]]


In [16]:
import numpy as np
array = np.array( [ [ [0,1,2,3], [4,5,6,7], [8,9,10,11] ], [ [12,13,14,15],[16,17,18,19],[20,21,22,23] ] ])
print("sum by row")
print(array.sum(axis=1))
print("sum by column")
print(array.sum(axis=0))


sum by row
[[12 15 18 21]
 [48 51 54 57]]
sum by column
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [18]:
# 2020.10.13 추가
np_array = np.arange(24).reshape(2,3,4)
print(np_array)
print()

# row별로 sum을 하면 (2,4)이 됨
sum_by_row = np_array.sum(axis=1)
print('sum by row \n', sum_by_row)
print(sum_by_row.shape)
print()

# columm별로 sum을 하면 (2,3)이 됨
column_by_row = np_array.sum(axis=2)
print('sub by column \n', column_by_row)
print(column_by_row.shape)
print()

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

sum by row 
 [[12 15 18 21]
 [48 51 54 57]]
(2, 4)

sub by column 
 [[ 6 22 38]
 [54 70 86]]
(2, 3)



In [21]:
import numpy as np
array1 = np.array(['apple','banana','grape'])
array2 = np.array(['apple','orange','grape'])
array3 = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
print(np.in1d(array2, array1))
print(np.intersect1d(array2, array1))
print(np.setdiff1d(array2, array1))
print(np.union1d(array2, array1))
print(np.union1d(array2, array1))
# print(np.intersect1d(array3, array3))
print(np.unique(array3)) #2020.10.13 추가, 중복된 원소를 제거


[ True False  True]
['apple' 'grape']
['orange']
['apple' 'banana' 'grape' 'orange']
['apple' 'banana' 'grape' 'orange']
[1 2 3 4 5 6]


In [22]:
# 2020.10.13 추가
print(array1[np.in1d(array1, array2)])

['apple' 'grape']


In [23]:
list(set(array3)) # set함수를 사용하여 unique한 원소를 얻게되는 효과를 얻게 됨

[1, 2, 3, 4, 5, 6]